[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255/32
dns-server = 223.5.5.5, 119.29.29.29
dns-fallback = true
ipv6 = false

[Proxy]
DIRECT = direct
美国-HY2-线路1 = hysteria2, s1.huhiuh.space, 28543, password=user028:35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, sni=www.bing.com, skip-cert-verify=true, obfs=salamander, obfs-password=sR7mK2xP9vN4wQ6jL1tF3bY8hA5cE0gZ
美国-VLESS-线路1 = vless, s1.huhiuh.space, 28543, password=35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, obfs=none, tls=true, sni=apple.com, udp-relay=true, flow=xtls-rprx-vision, reality=true, reality-public-key=rY6I8E6kJjbgmnwz5TSt8Tkb955J5C6_d6YE9qQCcFg, reality-short-id=ddbb5b71, client-fingerprint=chrome
美国-HY2-线路2 = hysteria2, s2.huhiuh.space, 28543, password=user028:35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, sni=www.bing.com, skip-cert-verify=true, obfs=salamander, obfs-password=sR7mK2xP9vN4wQ6jL1tF3bY8hA5cE0gZ
美国-VLESS-线路2 = vless, s2.huhiuh.space, 28543, password=35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, obfs=none, tls=true, sni=apple.com, udp-relay=true, flow=xtls-rprx-vision, reality=true, reality-public-key=rY6I8E6kJjbgmnwz5TSt8Tkb955J5C6_d6YE9qQCcFg, reality-short-id=ddbb5b71, client-fingerprint=chrome
美国-HY2-线路3 = hysteria2, s3.huhiuh.space, 28543, password=user028:35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, sni=www.bing.com, skip-cert-verify=true, obfs=salamander, obfs-password=sR7mK2xP9vN4wQ6jL1tF3bY8hA5cE0gZ
美国-VLESS-线路3 = vless, s3.huhiuh.space, 28543, password=35fbaeec-4e8a-4bd7-9f14-d7fed40892c1, obfs=none, tls=true, sni=apple.com, udp-relay=true, flow=xtls-rprx-vision, reality=true, reality-public-key=rY6I8E6kJjbgmnwz5TSt8Tkb955J5C6_d6YE9qQCcFg, reality-short-id=ddbb5b71, client-fingerprint=chrome

[Proxy Group]
自动选择 = url-test, 美国-HY2-线路1, 美国-VLESS-线路1, 美国-HY2-线路2, 美国-VLESS-线路2, 美国-HY2-线路3, 美国-VLESS-线路3, url=http://www.gstatic.com/generate_204, interval=5, tolerance=50

[Rule]
DOMAIN-KEYWORD,google,自动选择
DOMAIN-KEYWORD,gmail,自动选择
DOMAIN-KEYWORD,youtube,自动选择
DOMAIN-KEYWORD,facebook,自动选择
DOMAIN-KEYWORD,twitter,自动选择
DOMAIN-KEYWORD,instagram,自动选择
DOMAIN-KEYWORD,whatsapp,自动选择
DOMAIN-KEYWORD,telegram,自动选择
DOMAIN-KEYWORD,openai,自动选择
DOMAIN-KEYWORD,claude,自动选择
DOMAIN-SUFFIX,x.com,自动选择
DOMAIN-SUFFIX,t.co,自动选择
DOMAIN-SUFFIX,githubusercontent.com,自动选择
DOMAIN-SUFFIX,github.com,自动选择
DOMAIN-SUFFIX,wikipedia.org,自动选择
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN-SUFFIX,com.cn,DIRECT
DOMAIN-KEYWORD,baidu,DIRECT
DOMAIN-KEYWORD,alibaba,DIRECT
DOMAIN-KEYWORD,tencent,DIRECT
DOMAIN-KEYWORD,bilibili,DIRECT
DOMAIN-KEYWORD,weixin,DIRECT
DOMAIN-KEYWORD,douyin,DIRECT
DOMAIN-KEYWORD,deepseek,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
GEOIP,CN,DIRECT
FINAL,自动选择
